[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npm run build --workspace=@hospital-erp/frontend", "npm run build --workspace=@hospital-erp/backend"]

[start]
cmd = "node packages/backend/dist/index.js"