import { Router, Response } from 'express';
import { Prisma, ExamenStatut } from '@prisma/client';
import { prisma } from '../config/db.js';
import { authenticate, authorize, AuthRequest } from '../middleware/auth.js';
import { notifyMany } from '../services/notify.js';
import { patientAccessScope, canAccessPatient } from '../services/access-control.js';
import { assertTransition, WorkflowError } from '../services/workflow.js';

const router = Router();

// Single source of truth for the lab Kanban vocabulary, generated by
// Prisma from the ExamenStatut enum. Used both for runtime validation
// and for any TS-side comparison so a new statut value is a one-place
// change (schema.prisma + migration).
const ALLOWED_STATUTS: ReadonlySet<ExamenStatut> = new Set(
  Object.values(ExamenStatut) as ExamenStatut[],
);
function isValidStatut(v: unknown): v is ExamenStatut {
  return typeof v === 'string' && ALLOWED_STATUTS.has(v as ExamenStatut);
}

/**
 * When a lab result is newly added, notify whichever medecin is most likely
 * the requester. The schema has `examens.demandeur_id` but the create flow
 * doesn't always populate it; we fall back to the medecin of the patient's
 * most recent consultation. Both signals are best-effort.
 */
async function findResultRecipients(patientId: number, demandeurId: number | null | undefined): Promise<number[]> {
  if (demandeurId) return [demandeurId];
  // Fallback: medecin of the latest consultation, mapped to a user by name match
  const lastConsult = await prisma.consultation.findFirst({
    where: { patientId, medecinId: { not: null } },
    orderBy: { dateConsultation: 'desc' },
    select: { medecin: { select: { nom: true, prenom: true } } },
  });
  if (!lastConsult?.medecin) return [];
  const u = await prisma.user.findFirst({
    where: { role: 'medecin', nom: lastConsult.medecin.nom, prenom: lastConsult.medecin.prenom },
    select: { id: true },
  });
  return u ? [u.id] : [];
}

router.get('/', authenticate, async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { patient_id, date_debut, date_fin, statut } = req.query;
    const where: Prisma.ExamenWhereInput = {};
    if (patient_id) where.patientId = Number(patient_id);
    if (statut && isValidStatut(String(statut))) where.statut = String(statut) as ExamenStatut;
    if (date_debut || date_fin) {
      where.dateExamen = {};
      if (date_debut) (where.dateExamen as Prisma.DateTimeFilter).gte = new Date(String(date_debut));
      if (date_fin) (where.dateExamen as Prisma.DateTimeFilter).lte = new Date(String(date_fin));
    }
    const scope = await patientAccessScope(req.user!);
    if (scope.kind === 'restricted') {
      where.patientId = where.patientId
        ? (scope.ids.includes(where.patientId as number) ? where.patientId : -1)
        : { in: scope.ids };
    }
    const rows = await prisma.examen.findMany({
      where,
      include: { patient: { select: { nom: true, prenom: true, telephone: true } } },
      orderBy: [{ dateExamen: 'desc' }, { id: 'desc' }],
    });
    // Prisma returns camelCase (dateExamen, typeExamen, patientId, demandeurId).
    // The frontend Examen TS type + the Kanban / form read snake_case fields.
    // Without explicit mapping the dates render as "Invalid Date" and the edit
    // form initializes empty. Always emit snake_case from this surface.
    const mapped = rows.map(e => ({
      ...e,
      date_examen: e.dateExamen,
      type_examen: e.typeExamen,
      patient_id: e.patientId,
      demandeur_id: e.demandeurId,
      statut: e.statut,
      paye: e.paye,
      date_paiement: e.datePaiement,
      mode_paiement: e.modePaiement,
      patient_nom: e.patient?.nom ?? null,
      patient_prenom: e.patient?.prenom ?? null,
      patient_telephone: e.patient?.telephone ?? null,
    }));
    res.json(mapped);
  } catch (err) { res.status(500).json({ error: 'Erreur serveur' }); }
});

router.get('/stats', authenticate, async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { debut, fin } = req.query;
    const where: Prisma.ExamenWhereInput = {};
    if (debut && fin) {
      where.dateExamen = { gte: new Date(String(debut)), lte: new Date(String(fin)) };
    }
    const scope = await patientAccessScope(req.user!);
    if (scope.kind === 'restricted') where.patientId = { in: scope.ids };

    const totalAgg = await prisma.examen.aggregate({
      where,
      _count: { _all: true },
      _sum: { montant: true },
    });

    const parTypeGroup = await prisma.examen.groupBy({
      by: ['typeExamen'],
      where,
      _count: { _all: true },
      _sum: { montant: true },
    });

    const parType = parTypeGroup.map(g => ({
      type_examen: g.typeExamen,
      nb: g._count._all,
      revenus: g._sum.montant ?? 0,
    }));

    res.json({
      total: totalAgg._count._all,
      revenus: Number(totalAgg._sum.montant ?? 0),
      parType,
    });
  } catch (err) { res.status(500).json({ error: 'Erreur serveur' }); }
});

router.get('/:id', authenticate, async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const e = await prisma.examen.findUnique({
      where: { id: Number(req.params.id) },
      include: { patient: { select: { nom: true, prenom: true } } },
    });
    if (!e) { res.status(404).json({ error: 'Examen non trouvé' }); return; }
    if (!(await canAccessPatient(req.user!, e.patientId))) {
      res.status(403).json({ error: 'Accès refusé — ce patient ne vous est pas attribué' });
      return;
    }
    res.json({
      ...e,
      date_examen: e.dateExamen,
      type_examen: e.typeExamen,
      patient_id: e.patientId,
      demandeur_id: e.demandeurId,
      statut: e.statut,
      paye: e.paye,
      date_paiement: e.datePaiement,
      mode_paiement: e.modePaiement,
      patient_nom: e.patient?.nom ?? null,
      patient_prenom: e.patient?.prenom ?? null,
    });
  } catch (err) { res.status(500).json({ error: 'Erreur serveur' }); }
});

// Distinct exam types this patient has had before — used by ExamenForm to
// suggest "previously ordered" types alongside the standard list.
router.get('/patient/:patientId/types', authenticate, async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const patientId = Number(req.params.patientId);
    if (!(await canAccessPatient(req.user!, patientId))) {
      res.status(403).json({ error: 'Accès refusé — ce patient ne vous est pas attribué' });
      return;
    }
    const rows = await prisma.examen.findMany({
      where: { patientId },
      select: { typeExamen: true },
      distinct: ['typeExamen'],
      orderBy: { typeExamen: 'asc' },
      take: 50,
    });
    res.json(rows.map(r => r.typeExamen));
  } catch (err) { res.status(500).json({ error: 'Erreur serveur' }); }
});

router.post('/', authenticate, authorize('admin', 'laborantin'), async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { patient_id, type_examen, resultat, date_examen, montant } = req.body;
    const montantNum = montant !== undefined && montant !== null && montant !== '' ? Number(montant) : null;
    // Workflow gate: a non-zero-amount exam starts at 'a_payer' so it surfaces
    // in the cashier's lane before reaching prélèvement. Zero / free exams
    // skip straight to 'demande' (the prélèvement gate has no payment block).
    const initialStatut: ExamenStatut = montantNum && montantNum > 0 ? ExamenStatut.a_payer : ExamenStatut.demande;
    const data: Parameters<typeof prisma.examen.create>[0]['data'] = {
      patientId: Number(patient_id),
      typeExamen: type_examen,
      resultat: resultat ?? null,
      montant: montantNum,
      statut: initialStatut,
    };
    if (date_examen) data.dateExamen = new Date(date_examen);
    const created = await prisma.examen.create({ data });
    res.status(201).json(created);
  } catch (err) { res.status(500).json({ error: 'Erreur serveur' }); }
});

// Mark an exam as paid → flip paye=true, stamp date/mode, advance the
// Kanban to 'prelevement'. Audit trail captured via the standard log.
// Cashier action (not the lab): admin + comptable + reception. Laborantin
// is excluded because in the operational flow money is collected at the
// front desk, and the lab only sees the workflow advance to 'prelevement'.
router.post('/:id/marquer-paye', authenticate, authorize('admin', 'comptable', 'reception'), async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const id = Number(req.params.id);
    const { mode_paiement } = req.body as { mode_paiement?: string };
    const before = await prisma.examen.findUnique({ where: { id }, select: { paye: true, statut: true } });
    if (!before) { res.status(404).json({ error: 'Examen non trouvé' }); return; }
    if (before.paye) { res.status(400).json({ error: 'Examen déjà payé' }); return; }

    const updated = await prisma.examen.update({
      where: { id },
      data: {
        paye: true,
        datePaiement: new Date(),
        modePaiement: mode_paiement ? String(mode_paiement).substring(0, 50) : null,
        // Only advance the Kanban if it was sitting at 'a_payer'. If a user
        // marked something paid from a later state, keep the current statut.
        ...(before.statut === ExamenStatut.a_payer ? { statut: ExamenStatut.prelevement } : {}),
      },
    });
    res.json(updated);
  } catch (err) {
    console.error('[LABO] marquer-paye failed:', err);
    res.status(500).json({ error: 'Erreur serveur' });
  }
});

router.put('/:id', authenticate, authorize('admin', 'laborantin'), async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { type_examen, resultat, date_examen, montant, statut } = req.body;
    const data: Parameters<typeof prisma.examen.update>[0]['data'] = {};
    // Only set the fields the client actually sent so partial updates
    // (Kanban statut transition, result entry, edit form) don't accidentally
    // null out columns. The previous shape silently dropped `statut` on the
    // floor, which is why "Prélever" in the Kanban did nothing.
    if (type_examen !== undefined) data.typeExamen = type_examen;
    if (resultat !== undefined) data.resultat = resultat;
    if (montant !== undefined) data.montant = montant;
    if (date_examen) data.dateExamen = new Date(date_examen);
    if (statut !== undefined) {
      if (!isValidStatut(statut)) {
        res.status(400).json({ error: 'Statut invalide' });
        return;
      }
      data.statut = statut;
    }

    // Need the previous state to detect "result newly added" — null/empty → set —
    // and (when statut is changing) to validate the workflow transition.
    const before = await prisma.examen.findUnique({
      where: { id: Number(req.params.id) },
      select: { resultat: true, patientId: true, demandeurId: true, typeExamen: true, statut: true },
    });
    if (!before) { res.status(404).json({ error: 'Examen non trouvé' }); return; }

    if (statut !== undefined) {
      try { assertTransition('examen', before.statut, statut); }
      catch (e) {
        if (e instanceof WorkflowError) { res.status(400).json({ error: e.message }); return; }
        throw e;
      }
    }

    const updated = await prisma.examen.update({ where: { id: Number(req.params.id) }, data });

    const wasEmpty = !before.resultat || before.resultat.trim().length === 0;
    const nowFilled = typeof resultat === 'string' && resultat.trim().length > 0;
    if (wasEmpty && nowFilled) {
      try {
        const recipients = (await findResultRecipients(before.patientId, before.demandeurId)).filter(id => id !== req.user!.id);
        if (recipients.length > 0) {
          const patient = await prisma.patient.findUnique({ where: { id: before.patientId }, select: { nom: true, prenom: true } });
          const label = patient ? `${patient.prenom} ${patient.nom}` : `patient #${before.patientId}`;
          await notifyMany(recipients, {
            type: 'lab_validated',
            title: `Résultat de ${before.typeExamen} disponible`,
            body: `${label} — ${resultat.substring(0, 150)}`,
            link: `/app/patients/${before.patientId}#examens`,
          });
        }
      } catch (err) {
        console.error('[LABORATOIRE] result-ready notification failed:', err);
      }
    }

    res.json(updated);
  } catch (err) { res.status(500).json({ error: 'Erreur serveur' }); }
});

router.delete('/:id', authenticate, authorize('admin'), async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    try {
      await prisma.examen.delete({ where: { id: Number(req.params.id) } });
      res.json({ message: 'Examen supprimé' });
    } catch {
      res.status(404).json({ error: 'Examen non trouvé' });
    }
  } catch (err) { res.status(500).json({ error: 'Erreur serveur' }); }
});

export default router;
