import { Router, Response } from 'express';
import multer from 'multer';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import { Prisma, ExamenStatut, Priorite } from '@prisma/client';
import { prisma } from '../config/db.js';
import { authenticate, authorize, AuthRequest } from '../middleware/auth.js';
import { notifyMany } from '../services/notify.js';
import { patientAccessScope, canAccessPatient } from '../services/access-control.js';
import { assertTransition, WorkflowError } from '../services/workflow.js';
import { validateUpload, EXAMEN_FICHIER_MIMES } from '../middleware/upload-validation.js';
import { logAudit } from '../services/audit.js';

// Storage pour les pièces jointes des examens. Même pattern que
// imagerie : disque local, dossier dédié, nom sanitizé.
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const examenFichierDir = path.resolve(__dirname, '../../uploads/examens');
if (!fs.existsSync(examenFichierDir)) fs.mkdirSync(examenFichierDir, { recursive: true });
const examenFichierStorage = multer.diskStorage({
  destination: (_req, _file, cb) => cb(null, examenFichierDir),
  filename: (_req, file, cb) => cb(null, `${Date.now()}-${file.originalname.replace(/[^a-zA-Z0-9.-]/g, '_')}`),
});
const examenFichierUpload = multer({
  storage: examenFichierStorage,
  limits: { fileSize: 10 * 1024 * 1024 }, // 10 Mo — au-delà ça relève d'imagerie
  fileFilter: (_req, file, cb) => {
    const allowed = ['.pdf', '.png', '.jpg', '.jpeg', '.gif', '.bmp', '.zip', '.xlsx', '.xls'];
    cb(null, allowed.includes(path.extname(file.originalname).toLowerCase()));
  },
});

const router = Router();

// Single source of truth for the lab Kanban vocabulary, generated by
// Prisma from the ExamenStatut enum. Used both for runtime validation
// and for any TS-side comparison so a new statut value is a one-place
// change (schema.prisma + migration).
const ALLOWED_STATUTS: ReadonlySet<ExamenStatut> = new Set(
  Object.values(ExamenStatut) as ExamenStatut[],
);
function isValidStatut(v: unknown): v is ExamenStatut {
  return typeof v === 'string' && ALLOWED_STATUTS.has(v as ExamenStatut);
}
const ALLOWED_PRIORITES: ReadonlySet<Priorite> = new Set(
  Object.values(Priorite) as Priorite[],
);
function isValidPriorite(v: unknown): v is Priorite {
  return typeof v === 'string' && ALLOWED_PRIORITES.has(v as Priorite);
}

/**
 * When a lab result is newly added, notify whichever medecin is most likely
 * the requester. The schema has `examens.demandeur_id` but the create flow
 * doesn't always populate it; we fall back to the medecin of the patient's
 * most recent consultation. Both signals are best-effort.
 */
async function findResultRecipients(patientId: number, demandeurId: number | null | undefined): Promise<number[]> {
  if (demandeurId) return [demandeurId];
  // Fallback: medecin of the latest consultation, mapped to a user by name match
  const lastConsult = await prisma.consultation.findFirst({
    where: { patientId, medecinId: { not: null } },
    orderBy: { dateConsultation: 'desc' },
    select: { medecin: { select: { nom: true, prenom: true } } },
  });
  if (!lastConsult?.medecin) return [];
  const u = await prisma.user.findFirst({
    where: { role: 'medecin', nom: lastConsult.medecin.nom, prenom: lastConsult.medecin.prenom },
    select: { id: true },
  });
  return u ? [u.id] : [];
}

/**
 * Détermine le médecin demandeur d'un examen.
 *   - utilisateur connecté médecin  → c'est lui le prescripteur.
 *   - sinon                         → le médecin choisi dans le formulaire,
 *     validé comme étant bien un utilisateur de rôle medecin.
 * Renvoie null si rien d'exploitable (examen sans prescripteur connu).
 */
async function resolveDemandeur(
  user: NonNullable<AuthRequest['user']>,
  demandeurIdRaw: unknown,
): Promise<number | null> {
  if (user.role === 'medecin') return user.id;
  const id = Number(demandeurIdRaw);
  if (!Number.isInteger(id) || id <= 0) return null;
  const medecin = await prisma.user.findFirst({ where: { id, role: 'medecin' }, select: { id: true } });
  return medecin?.id ?? null;
}

router.get('/', authenticate, async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { patient_id, date_debut, date_fin, statut } = req.query;
    const where: Prisma.ExamenWhereInput = {};
    if (patient_id) where.patientId = Number(patient_id);
    if (statut && isValidStatut(String(statut))) where.statut = String(statut) as ExamenStatut;
    if (date_debut || date_fin) {
      where.dateExamen = {};
      if (date_debut) (where.dateExamen as Prisma.DateTimeFilter).gte = new Date(String(date_debut));
      if (date_fin) (where.dateExamen as Prisma.DateTimeFilter).lte = new Date(String(date_fin));
    }
    const scope = await patientAccessScope(req.user!);
    if (scope.kind === 'restricted') {
      where.patientId = where.patientId
        ? (scope.ids.includes(where.patientId as number) ? where.patientId : -1)
        : { in: scope.ids };
    }
    const rows = await prisma.examen.findMany({
      where,
      include: { patient: { select: { nom: true, prenom: true, telephone: true } } },
      // Priorité d'abord — Prisma's enum sort is by declaration order
      // so urgent (0) < prioritaire (1) < normal (2) lands naturally.
      orderBy: [{ priorite: 'asc' }, { dateExamen: 'desc' }, { id: 'desc' }],
    });
    const mapped = rows.map(e => ({
      ...e,
      date_examen: e.dateExamen,
      type_examen: e.typeExamen,
      patient_id: e.patientId,
      demandeur_id: e.demandeurId,
      statut: e.statut,
      priorite: e.priorite,
      paye: e.paye,
      date_paiement: e.datePaiement,
      mode_paiement: e.modePaiement,
      patient_nom: e.patient?.nom ?? null,
      patient_prenom: e.patient?.prenom ?? null,
      patient_telephone: e.patient?.telephone ?? null,
    }));
    res.json(mapped);
  } catch (err) { res.status(500).json({ error: 'Erreur serveur' }); }
});

router.get('/stats', authenticate, async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { debut, fin } = req.query;
    const where: Prisma.ExamenWhereInput = {};
    if (debut && fin) {
      where.dateExamen = { gte: new Date(String(debut)), lte: new Date(String(fin)) };
    }
    const scope = await patientAccessScope(req.user!);
    if (scope.kind === 'restricted') where.patientId = { in: scope.ids };

    const totalAgg = await prisma.examen.aggregate({
      where,
      _count: { _all: true },
      _sum: { montant: true },
    });

    const parTypeGroup = await prisma.examen.groupBy({
      by: ['typeExamen'],
      where,
      _count: { _all: true },
      _sum: { montant: true },
    });

    const parType = parTypeGroup.map(g => ({
      type_examen: g.typeExamen,
      nb: g._count._all,
      revenus: g._sum.montant ?? 0,
    }));

    res.json({
      total: totalAgg._count._all,
      revenus: Number(totalAgg._sum.montant ?? 0),
      parType,
    });
  } catch (err) { res.status(500).json({ error: 'Erreur serveur' }); }
});

router.get('/:id', authenticate, async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const e = await prisma.examen.findUnique({
      where: { id: Number(req.params.id) },
      include: { patient: { select: { nom: true, prenom: true } } },
    });
    if (!e) { res.status(404).json({ error: 'Examen non trouvé' }); return; }
    if (!(await canAccessPatient(req.user!, e.patientId))) {
      res.status(403).json({ error: 'Accès refusé — ce patient ne vous est pas attribué' });
      return;
    }
    res.json({
      ...e,
      date_examen: e.dateExamen,
      type_examen: e.typeExamen,
      patient_id: e.patientId,
      demandeur_id: e.demandeurId,
      statut: e.statut,
      paye: e.paye,
      date_paiement: e.datePaiement,
      mode_paiement: e.modePaiement,
      patient_nom: e.patient?.nom ?? null,
      patient_prenom: e.patient?.prenom ?? null,
    });
  } catch (err) { res.status(500).json({ error: 'Erreur serveur' }); }
});

// Distinct exam types this patient has had before — used by ExamenForm to
// suggest "previously ordered" types alongside the standard list.
router.get('/patient/:patientId/types', authenticate, async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const patientId = Number(req.params.patientId);
    if (!(await canAccessPatient(req.user!, patientId))) {
      res.status(403).json({ error: 'Accès refusé — ce patient ne vous est pas attribué' });
      return;
    }
    const rows = await prisma.examen.findMany({
      where: { patientId },
      select: { typeExamen: true },
      distinct: ['typeExamen'],
      orderBy: { typeExamen: 'asc' },
      take: 50,
    });
    res.json(rows.map(r => r.typeExamen));
  } catch (err) { res.status(500).json({ error: 'Erreur serveur' }); }
});

// Examen creation is also open to medecin — clinicians need to order
// labs from the patient chart without depending on a laborantin to
// type the request in. Result entry / Kanban moves stay
// laborantin-only via the other routes.
router.post('/', authenticate, authorize('admin', 'laborantin', 'medecin'), async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { patient_id, type_examen, resultat, date_examen, montant, priorite, demandeur_id } = req.body;
    const montantNum = montant !== undefined && montant !== null && montant !== '' ? Number(montant) : null;
    const initialStatut: ExamenStatut = montantNum && montantNum > 0 ? ExamenStatut.a_payer : ExamenStatut.demande;
    const initialPriorite: Priorite = isValidPriorite(priorite) ? priorite : Priorite.normal;
    // Prescripteur : si l'utilisateur connecté est médecin, c'est lui le
    // demandeur ; sinon (laborantin/admin/réception) on prend le médecin
    // choisi dans le formulaire. On valide que l'id désigne bien un médecin.
    const demandeurId = await resolveDemandeur(req.user!, demandeur_id);
    const data: Parameters<typeof prisma.examen.create>[0]['data'] = {
      patientId: Number(patient_id),
      typeExamen: type_examen,
      resultat: resultat ?? null,
      montant: montantNum,
      statut: initialStatut,
      priorite: initialPriorite,
      demandeurId,
    };
    if (date_examen) data.dateExamen = new Date(date_examen);
    const created = await prisma.examen.create({ data });
    res.status(201).json(created);
  } catch (err) { res.status(500).json({ error: 'Erreur serveur' }); }
});

// Mark an exam as paid → flip paye=true, stamp date/mode, advance the
// Kanban to 'prelevement'. Audit trail captured via the standard log.
// Cashier action (not the lab): admin + comptable + reception. Laborantin
// is excluded because in the operational flow money is collected at the
// front desk, and the lab only sees the workflow advance to 'prelevement'.
router.post('/:id/marquer-paye', authenticate, authorize('admin', 'comptable', 'reception'), async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const id = Number(req.params.id);
    const { mode_paiement } = req.body as { mode_paiement?: string };
    const before = await prisma.examen.findUnique({ where: { id }, select: { paye: true, statut: true } });
    if (!before) { res.status(404).json({ error: 'Examen non trouvé' }); return; }
    if (before.paye) { res.status(400).json({ error: 'Examen déjà payé' }); return; }

    const updated = await prisma.examen.update({
      where: { id },
      data: {
        paye: true,
        datePaiement: new Date(),
        modePaiement: mode_paiement ? String(mode_paiement).substring(0, 50) : null,
        // Only advance the Kanban if it was sitting at 'a_payer'. If a user
        // marked something paid from a later state, keep the current statut.
        ...(before.statut === ExamenStatut.a_payer ? { statut: ExamenStatut.prelevement } : {}),
      },
    });
    res.json(updated);
  } catch (err) {
    console.error('[LABO] marquer-paye failed:', err);
    res.status(500).json({ error: 'Erreur serveur' });
  }
});

router.put('/:id', authenticate, authorize('admin', 'laborantin'), async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { type_examen, resultat, date_examen, montant, statut, priorite, demandeur_id } = req.body;
    const data: Parameters<typeof prisma.examen.update>[0]['data'] = {};
    if (type_examen !== undefined) data.typeExamen = type_examen;
    if (resultat !== undefined) data.resultat = resultat;
    if (montant !== undefined) data.montant = montant;
    if (date_examen) data.dateExamen = new Date(date_examen);
    if (demandeur_id !== undefined) data.demandeurId = await resolveDemandeur(req.user!, demandeur_id);
    if (statut !== undefined) {
      if (!isValidStatut(statut)) {
        res.status(400).json({ error: 'Statut invalide' });
        return;
      }
      data.statut = statut;
    }
    if (priorite !== undefined) {
      if (!isValidPriorite(priorite)) {
        res.status(400).json({ error: 'Priorité invalide' });
        return;
      }
      data.priorite = priorite;
    }

    // Need the previous state to detect "result newly added" — null/empty → set —
    // and (when statut is changing) to validate the workflow transition.
    const before = await prisma.examen.findUnique({
      where: { id: Number(req.params.id) },
      select: { resultat: true, patientId: true, demandeurId: true, typeExamen: true, statut: true },
    });
    if (!before) { res.status(404).json({ error: 'Examen non trouvé' }); return; }

    if (statut !== undefined) {
      try { assertTransition('examen', before.statut, statut); }
      catch (e) {
        if (e instanceof WorkflowError) { res.status(400).json({ error: e.message }); return; }
        throw e;
      }
    }

    const updated = await prisma.examen.update({ where: { id: Number(req.params.id) }, data });

    const wasEmpty = !before.resultat || before.resultat.trim().length === 0;
    const nowFilled = typeof resultat === 'string' && resultat.trim().length > 0;
    if (wasEmpty && nowFilled) {
      try {
        const recipients = (await findResultRecipients(before.patientId, before.demandeurId)).filter(id => id !== req.user!.id);
        if (recipients.length > 0) {
          const patient = await prisma.patient.findUnique({ where: { id: before.patientId }, select: { nom: true, prenom: true } });
          const label = patient ? `${patient.prenom} ${patient.nom}` : `patient #${before.patientId}`;
          await notifyMany(recipients, {
            type: 'lab_validated',
            title: `Résultat de ${before.typeExamen} disponible`,
            body: `${label} — ${resultat.substring(0, 150)}`,
            link: `/app/patients/${before.patientId}#examens`,
          });
        }
      } catch (err) {
        console.error('[LABORATOIRE] result-ready notification failed:', err);
      }
    }

    res.json(updated);
  } catch (err) { res.status(500).json({ error: 'Erreur serveur' }); }
});

router.delete('/:id', authenticate, authorize('admin'), async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    try {
      await prisma.examen.delete({ where: { id: Number(req.params.id) } });
      res.json({ message: 'Examen supprimé' });
    } catch {
      res.status(404).json({ error: 'Examen non trouvé' });
    }
  } catch (err) { res.status(500).json({ error: 'Erreur serveur' }); }
});

// === Pièces jointes ===

// List : tout utilisateur ayant accès au patient peut voir les fichiers.
router.get('/:id/fichiers', authenticate, async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const examen = await prisma.examen.findUnique({ where: { id: Number(req.params.id) }, select: { patientId: true } });
    if (!examen) { res.status(404).json({ error: 'Examen non trouvé' }); return; }
    if (!(await canAccessPatient(req.user!, examen.patientId))) {
      res.status(403).json({ error: 'Accès refusé' });
      return;
    }
    const rows = await prisma.examenFichier.findMany({
      where: { examenId: Number(req.params.id) },
      orderBy: { createdAt: 'desc' },
    });
    res.json(rows.map(f => ({
      ...f,
      // Décor pour le frontend (camelCase déjà, mais on aligne sur le reste de l'API).
      examen_id: f.examenId,
      fichier_url: f.fichierUrl,
      fichier_nom: f.fichierNom,
      fichier_type: f.fichierType,
      fichier_taille: f.fichierTaille,
      uploaded_by_id: f.uploadedById,
      created_at: f.createdAt,
    })));
  } catch (err) { console.error('[LABO] list fichiers failed:', err); res.status(500).json({ error: 'Erreur serveur' }); }
});

// Upload : l'examen doit avoir au moins atteint 'analyse'. Multer écrit
// d'abord sur disque, validateUpload vérifie les magic bytes, puis on
// crée la ligne ExamenFichier.
router.post('/:id/fichiers', authenticate, authorize('admin', 'laborantin', 'medecin'), examenFichierUpload.single('file'), validateUpload(EXAMEN_FICHIER_MIMES), async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    if (!req.file) { res.status(400).json({ error: 'Fichier requis' }); return; }
    const id = Number(req.params.id);
    const examen = await prisma.examen.findUnique({ where: { id }, select: { statut: true, patientId: true } });
    if (!examen) {
      try { if (req.file?.path) fs.unlinkSync(req.file.path); } catch { /* ignore */ }
      res.status(404).json({ error: 'Examen non trouvé' });
      return;
    }
    // Les fichiers ne sont uploadables qu'à partir du moment où le
    // laborantin commence l'analyse. En amont (demande / a_payer /
    // prelevement) il n'y a rien à joindre.
    const allowed: ExamenStatut[] = [ExamenStatut.analyse, ExamenStatut.resultat, ExamenStatut.valide, ExamenStatut.transmis];
    if (!allowed.includes(examen.statut)) {
      try { if (req.file?.path) fs.unlinkSync(req.file.path); } catch { /* ignore */ }
      res.status(409).json({ error: `Statut ${examen.statut} : les fichiers sont uploadables à partir de 'analyse'` });
      return;
    }

    const fichierUrl = `/uploads/examens/${req.file.filename}`;
    const notes = typeof req.body?.notes === 'string' ? req.body.notes.substring(0, 500) : null;

    const created = await prisma.examenFichier.create({
      data: {
        examenId: id,
        fichierUrl,
        fichierNom: req.file.originalname.substring(0, 255),
        fichierType: req.file.mimetype.substring(0, 100),
        fichierTaille: req.file.size,
        notes,
        uploadedById: req.user!.id,
      },
    });

    await logAudit({
      userId: req.user!.id, action: 'create', tableName: 'examen_fichiers', recordId: created.id,
      details: `Fichier ${req.file.originalname} (${req.file.size} octets) joint à examen #${id}`,
    });

    res.status(201).json({
      ...created,
      examen_id: created.examenId,
      fichier_url: created.fichierUrl,
      fichier_nom: created.fichierNom,
      fichier_type: created.fichierType,
      fichier_taille: created.fichierTaille,
      uploaded_by_id: created.uploadedById,
      created_at: created.createdAt,
    });
  } catch (err) {
    console.error('[LABO] upload fichier failed:', err);
    try { if (req.file?.path) fs.unlinkSync(req.file.path); } catch { /* ignore */ }
    res.status(500).json({ error: 'Erreur serveur' });
  }
});

// Delete : admin + laborantin + l'auteur de l'upload.
router.delete('/:id/fichiers/:fichierId', authenticate, async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const fichierId = Number(req.params.fichierId);
    const fichier = await prisma.examenFichier.findUnique({ where: { id: fichierId } });
    if (!fichier || fichier.examenId !== Number(req.params.id)) {
      res.status(404).json({ error: 'Fichier non trouvé' });
      return;
    }
    const u = req.user!;
    const canDelete = u.role === 'admin' || u.role === 'laborantin' || fichier.uploadedById === u.id;
    if (!canDelete) { res.status(403).json({ error: 'Non autorisé' }); return; }

    await prisma.examenFichier.delete({ where: { id: fichierId } });

    // Nettoyage du fichier sur disque — best-effort.
    try {
      const localPath = path.resolve(examenFichierDir, path.basename(fichier.fichierUrl));
      if (localPath.startsWith(examenFichierDir) && fs.existsSync(localPath)) fs.unlinkSync(localPath);
    } catch (err) { console.warn('[LABO] unlink failed:', err); }

    await logAudit({
      userId: u.id, action: 'delete', tableName: 'examen_fichiers', recordId: fichierId,
      details: `Fichier ${fichier.fichierNom} supprimé`,
    });

    res.json({ message: 'Fichier supprimé' });
  } catch (err) {
    console.error('[LABO] delete fichier failed:', err);
    res.status(500).json({ error: 'Erreur serveur' });
  }
});

export default router;
